// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckCloseDialog() {
  return window['go']['main']['App']['AckCloseDialog']();
}

export function AddBookmark(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBookmark'](arg1, arg2, arg3);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function BackupData() {
  return window['go']['main']['App']['BackupData']();
}

export function BookmarksFor(arg1) {
  return window['go']['main']['App']['BookmarksFor'](arg1);
}

export function CancelQueuedTransfers() {
  return window['go']['main']['App']['CancelQueuedTransfers']();
}

export function CancelQuit() {
  return window['go']['main']['App']['CancelQuit']();
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function CancelTransfers(arg1) {
  return window['go']['main']['App']['CancelTransfers'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearDoneTransfers() {
  return window['go']['main']['App']['ClearDoneTransfers']();
}

export function ClearFailedTransfers(arg1) {
  return window['go']['main']['App']['ClearFailedTransfers'](arg1);
}

export function CloseToPill() {
  return window['go']['main']['App']['CloseToPill']();
}

export function ConfirmQuit() {
  return window['go']['main']['App']['ConfirmQuit']();
}

export function ConnectSite(arg1) {
  return window['go']['main']['App']['ConnectSite'](arg1);
}

export function DataLocation() {
  return window['go']['main']['App']['DataLocation']();
}

export function DeleteBookmark(arg1) {
  return window['go']['main']['App']['DeleteBookmark'](arg1);
}

export function DeleteLocal(arg1, arg2) {
  return window['go']['main']['App']['DeleteLocal'](arg1, arg2);
}

export function DeleteLocalPermanently(arg1, arg2) {
  return window['go']['main']['App']['DeleteLocalPermanently'](arg1, arg2);
}

export function DeleteRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRemote'](arg1, arg2, arg3);
}

export function DeleteSite(arg1) {
  return window['go']['main']['App']['DeleteSite'](arg1);
}

export function DisconnectSite(arg1) {
  return window['go']['main']['App']['DisconnectSite'](arg1);
}

export function DiskSpace(arg1) {
  return window['go']['main']['App']['DiskSpace'](arg1);
}

export function DismissUpdate(arg1) {
  return window['go']['main']['App']['DismissUpdate'](arg1);
}

export function EnqueueDownloads(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnqueueDownloads'](arg1, arg2, arg3);
}

export function EnqueueUploads(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnqueueUploads'](arg1, arg2, arg3);
}

export function EnqueueUploadsFromPaths(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnqueueUploadsFromPaths'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportSites(arg1) {
  return window['go']['main']['App']['ImportSites'](arg1);
}

export function ListLocal(arg1) {
  return window['go']['main']['App']['ListLocal'](arg1);
}

export function ListRemote(arg1, arg2) {
  return window['go']['main']['App']['ListRemote'](arg1, arg2);
}

export function LocalHome() {
  return window['go']['main']['App']['LocalHome']();
}

export function LocalRoots() {
  return window['go']['main']['App']['LocalRoots']();
}

export function LogDir() {
  return window['go']['main']['App']['LogDir']();
}

export function MkdirLocal(arg1, arg2) {
  return window['go']['main']['App']['MkdirLocal'](arg1, arg2);
}

export function MkdirRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['MkdirRemote'](arg1, arg2, arg3);
}

export function MoveLocal(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveLocal'](arg1, arg2, arg3);
}

export function MoveRemote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveRemote'](arg1, arg2, arg3, arg4);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function PauseTransfer(arg1) {
  return window['go']['main']['App']['PauseTransfer'](arg1);
}

export function PickFile(arg1) {
  return window['go']['main']['App']['PickFile'](arg1);
}

export function QueuePaused() {
  return window['go']['main']['App']['QueuePaused']();
}

export function RemoteHome(arg1) {
  return window['go']['main']['App']['RemoteHome'](arg1);
}

export function RenameLocal(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameLocal'](arg1, arg2, arg3);
}

export function RenameRemote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameRemote'](arg1, arg2, arg3, arg4);
}

export function ResolveConflicts(arg1, arg2) {
  return window['go']['main']['App']['ResolveConflicts'](arg1, arg2);
}

export function ResolvePrompt(arg1, arg2) {
  return window['go']['main']['App']['ResolvePrompt'](arg1, arg2);
}

export function ResumeTransfer(arg1) {
  return window['go']['main']['App']['ResumeTransfer'](arg1);
}

export function RetryFailedTransfers() {
  return window['go']['main']['App']['RetryFailedTransfers']();
}

export function SaveSite(arg1, arg2) {
  return window['go']['main']['App']['SaveSite'](arg1, arg2);
}

export function SchemaVersion() {
  return window['go']['main']['App']['SchemaVersion']();
}

export function SetMiniMode(arg1) {
  return window['go']['main']['App']['SetMiniMode'](arg1);
}

export function SetQueuePaused(arg1) {
  return window['go']['main']['App']['SetQueuePaused'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetSiteRemotePath(arg1, arg2) {
  return window['go']['main']['App']['SetSiteRemotePath'](arg1, arg2);
}

export function Sites() {
  return window['go']['main']['App']['Sites']();
}

export function StartDragOut(arg1, arg2) {
  return window['go']['main']['App']['StartDragOut'](arg1, arg2);
}

export function TransferHistory() {
  return window['go']['main']['App']['TransferHistory']();
}

export function TransfersList() {
  return window['go']['main']['App']['TransfersList']();
}

export function UpdateRepo() {
  return window['go']['main']['App']['UpdateRepo']();
}
